/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Christian Lüdeking (https://sketchfab.com/happitack)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cozy-lake-55d48e0250384ed9811c1567fd3fa7fd
Title: Cozy Lake
*/

import React, { useRef, useState} from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree} from '@react-three/fiber'
import danauScene from '../assets/cozy_lake.glb'
import { a } from '@react-spring/three'

const Danau = ({onCloudClick}, props) => {
  const danauRef = useRef();
  const { nodes, materials } = useGLTF(danauScene);
  const handleCloudClick = (cloudName) => {
    onCloudClick(cloudName); // Kirim nama awan ke parent component
  };
  return (
    <a.group ref={danauRef} {...props} >
      <group position={[31.11, 24.07, 9.98]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, -94.27]}>
          <mesh
            geometry={nodes.Island_01_Water_0.geometry}
            material={materials.Water}
          />
          <mesh
            geometry={nodes.Island_01_Sand_0.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Island_01_Dirt_0.geometry}
            material={materials.Dirt}
          />
        </group>
      </group>
      <group position={[7.28, -61.11, -170.32]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[16.35, -191.47, -23.62]}>
          <mesh
            geometry={nodes.Pipe_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            geometry={nodes.Pipe_Water_0.geometry}
            material={materials.Water}
          />
        </group>
      </group>
      <group position={[-145.2, 18.22, 129.3]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Tree_Dense_01_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Dense_01_Leaf_0.geometry}
          material={materials.Leaf}
        />
      </group>
      <group position={[-70.43, 17.29, 198.91]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Tree_Bare_01_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Bare_01_Branch_0.geometry}
          material={materials.Branch}
        />
      </group>
      <group
        position={[229.9, 16.97, 41.9]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.35}
      >
        <mesh
          geometry={nodes.Tree_Dense_002_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Dense_002_Leaf_0.geometry}
          material={materials.Leaf}
        />
      </group>
      <group
        position={[113.55, 13.81, -198.4]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.35}
      >
        <mesh
          geometry={nodes.Tree_Dense_003_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Dense_003_Leaf_0.geometry}
          material={materials.Leaf}
        />
      </group>
      <group position={[-15.15, 16.04, 212.96]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Tree_Pine_01_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Pine_01_Leaf_0.geometry}
          material={materials.Leaf}
        />
      </group>
      <group position={[-199.76, 15.83, 31.8]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Tree_Pine_003_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Pine_003_Leaf_0.geometry}
          material={materials.Leaf}
        />
      </group>
      <group
        position={[109.63, 11.22, 201.05]}
        rotation={[-1.59, -0.17, -0.19]}
      >
        <mesh
          geometry={nodes.Tree_Bare_002_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Bare_002_Branch_0.geometry}
          material={materials.Branch}
        />
      </group>
      <group
        position={[208.66, 14.68, -104.41]}
        rotation={[-1.63, -0.02, -0.33]}
      >
        <mesh
          geometry={nodes.Tree_Bare_003_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Bare_003_Branch_0.geometry}
          material={materials.Branch}
        />
      </group>
      <group
        position={[145.21, 17, -181.04]}
        rotation={[-1.81, 0.4, 0.54]}
        scale={[0.74, 1.35, 1.35]}
      >
        <mesh
          geometry={nodes.Stone1_002_Dirt_0.geometry}
          material={materials.Dirt}
          position={[-2.04, 12.41, -0.3]}
        />
      </group>
      <group position={[-211.89, 7.03, 33.4]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.TreeRoot_01_Wood_0.geometry}
          material={materials.Wood}
          position={[12.13, 1.6, 8.81]}
        />
      </group>
      <group position={[183.15, 11.87, -134.4]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Tree_Dense_Red_01_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Dense_Red_01_Leaf_Red_0.geometry}
          material={materials.Leaf_Red}
        />
      </group>
      <group position={[210.77, 13.39, 166.22]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Tree_Dense_Red_002_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Dense_Red_002_Leaf_Red_0.geometry}
          material={materials.Leaf_Red}
        />
      </group>
      <group position={[-179.58, 18.22, -9.69]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Tree_Dense_Red_003_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Dense_Red_003_Leaf_Red_0.geometry}
          material={materials.Leaf_Red}
        />
      </group>
      <mesh
      position={[2, 50, 780]}
      onClick={() => handleCloudClick('Cloud Info')}
      onPointerOver={(e) => e.stopPropagation()} // Mencegah event pointer menyebar
    >
      <sphereGeometry args={[1, 32, 32]} /> {/* Ukuran bola */}
      <meshStandardMaterial color="white" /> {/* Warna bola */}
    </mesh>
      <group position={[-96.9, 18.22, 184.24]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Tree_Dense_Yellow_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes["Tree_Dense_Yellow_Material_#3_0"].geometry}
          material={materials.Material_3}
        />
      </group>
      <group position={[227.24, 17.8, -40.54]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Tree_Pine_004_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes["Tree_Pine_004_Material_#3_0"].geometry}
          material={materials.Material_3}
        />
      </group>
      <group position={[101.59, 19.52, -192.26]} rotation={[-1.9, 0.06, 2.97]}>
        <mesh
          geometry={nodes["Mushroom_05_Material_#26_0"].geometry}
          material={materials.Material_26}
        />
        <mesh
          geometry={nodes.Mushroom_05_Metal_0.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Mushroom_05_Rock_0.geometry}
          material={materials.Rock}
        />
      </group>
      <group
        position={[-182.69, 19.53, -19.56]}
        rotation={[-1.59, -0.15, 2.99]}
      >
        <mesh
          geometry={nodes["Mushroom_01_Material_#26_0"].geometry}
          material={materials.Material_26}
        />
        <mesh
          geometry={nodes.Mushroom_01_Metal_0.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Mushroom_01_Rock_0.geometry}
          material={materials.Rock}
        />
      </group>
      <group position={[91.17, 17.26, 198.49]} rotation={[-1.35, 0.07, 3.01]}>
        <mesh
          geometry={nodes["Mushroom_02_Material_#26_0"].geometry}
          material={materials.Material_26}
        />
        <mesh
          geometry={nodes.Mushroom_02_Metal_0.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Mushroom_02_Rock_0.geometry}
          material={materials.Rock}
        />
      </group>
      <group position={[227.56, 18.36, 7.65]} rotation={[-1.55, 0.23, 3.05]}>
        <mesh
          geometry={nodes["Mushroom_04_Material_#26_0"].geometry}
          material={materials.Material_26}
        />
        <mesh
          geometry={nodes.Mushroom_04_Metal_0.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Mushroom_04_Rock_0.geometry}
          material={materials.Rock}
        />
      </group>
      <group position={[-75.43, 108.19, -31.83]} scale={4.67}>
        <group position={[-1.62, -4.96, 0.63]}>
          <mesh
            geometry={nodes.polySurface1_lambert6_0.geometry}
            material={materials.lambert6}
          />
          <mesh
            geometry={nodes.polySurface1_lambert7_0.geometry}
            material={materials.lambert7}
          />
        </group>
      </group>
      <group position={[-114.8, 21.11, -116.66]} rotation={[-1.82, -0.06, 3]}>
        <mesh
          geometry={nodes.Tree_Stump_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Tree_Stump_Rock_0.geometry}
          material={materials.Rock}
        />
      </group>
      <group
        position={[-126.62, 20.62, -116.35]}
        rotation={[-1.82, -0.06, 2.97]}
      >
        <mesh
          geometry={nodes["Mushroom_006_Material_#26_0"].geometry}
          material={materials.Material_26}
        />
        <mesh
          geometry={nodes.Mushroom_006_Metal_0.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Mushroom_006_Rock_0.geometry}
          material={materials.Rock}
        />
      </group>
      <group
        position={[-113.26, 26.41, 23.22]}
        rotation={[-Math.PI / 2, 0.04, 0]}
        scale={[0.96, 1.04, 0.87]}
      >
        <group rotation={[0, 0, -Math.PI / 9]}>
          <mesh
            geometry={nodes.Boat_Sand_0.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Boat_Rock_0.geometry}
            material={materials.Rock}
          />
          <mesh
            geometry={nodes.Boat_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            geometry={nodes.Boat_Wood_0.geometry}
            material={materials.Wood}
          />
        </group>
      </group>
      <group position={[-112.25, 34.01, 36.53]} rotation={[0, -0.02, 0]}>
        <mesh
          geometry={nodes.Cylinder006_Sand_0.geometry}
          material={materials.Sand}
          position={[0, 0, -4.86]}
        />
      </group>
      <group
        position={[-111.83, 34.01, 10.26]}
        rotation={[3.14, 0.02, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cylinder007_Sand_0.geometry}
          material={materials.Sand}
          position={[0, 0, -4.86]}
        />
      </group>
      <mesh
        geometry={nodes.Stone1_01_Dirt_0.geometry}
        material={materials.Dirt}
        position={[69.73, 12.55, 211.62]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Stone2_01_Dirt_0.geometry}
        material={materials.Dirt}
        position={[35.54, 4.6, 214.25]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Stone2_002_Dirt_0.geometry}
        material={materials.Dirt}
        position={[-178.01, 19.52, 71.32]}
        rotation={[-1.51, -0.15, 1.46]}
      />
      <mesh
        geometry={nodes.Cylinder001_Wood_0.geometry}
        material={materials.Wood}
        position={[-172, 23.58, -26.52]}
        rotation={[-1.78, -0.28, 2.13]}
        scale={[1.37, 1, 1]}
      />
      <mesh
        geometry={nodes.Cloud02_lambert2_0.geometry}
        material={materials.lambert2}
        position={[85.18, 11.17, -288.68]}
        rotation={[0, Math.PI / 6, 0]}
        scale={16.18}
      />
      <mesh
        geometry={nodes.Cloud01_lambert3_0.geometry}
        material={materials.lambert3}
        position={[-263.17, -5.33, -123.51]}
        rotation={[-Math.PI / 2, 0, Math.PI / 9]}
        scale={2.08}
      />
      <mesh
        geometry={nodes.Cloud03_lambert3_0.geometry}
        material={materials.lambert3}
        position={[360.13, 39.29, 137.46]}
        rotation={[2.6, -0.26, 2.89]}
        scale={1.09}
      />
      <mesh
        geometry={nodes.Stone2_003_Dirt_0.geometry}
        material={materials.Dirt}
        position={[-139.34, 6.55, -102.55]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </a.group>
  );
}

export default Danau;